"""P-040 — THE SAMPLE REFRESH: the committed two-producer demo trees.

``examples/`` carries the differential in committed form — two artifact
trees generated by the real CLI from the SAME stems (the seeded
``vocal_chop_groove`` fixture, the differential's showcase):

    examples/sample_output/            <- the reference run (halee_ramone)
    examples/sample_output_timbaland/  <- --producer timbaland

THE STALENESS PIN (the packet's judgment call, taken at FULL strength):
each committed tree must byte-match a freshly generated run — the same
file-name set, every file byte-identical, modulo exactly ONE documented
normalization (the stems-path input echo in two artifacts — the committed
trees carry the portable relative form). The P-038 standing note this
packet clears existed because the old sample tree shipped stale
pre-P-036/P-038 prose from an earlier fixture/contract era; with this pin
the samples can never silently rot again. Full-tree comparison is CHEAP
here by construction: the analyses are the session-scoped
``chop_groove_analyzed`` fixture (already computed for the P-035/P-032i
suites) and ``write_artifacts`` is pure rendering — and P-039 pinned that
the CLI tree byte-matches the library ``write_artifacts`` tree, so the
library run is an honest stand-in for the committed trees' actual CLI
provenance. Determinism is real (seeded fixture; two consecutive CLI
regenerations were byte-identical at commit time).

The headline pin re-reads the committed files DIRECTLY: the README's
"Two producers, same stems" table quotes exactly these values, so the
docs' claims stay machine-checked even though the staleness pin already
implies them transitively.
"""

from __future__ import annotations

import json

import pytest

from logic_mix_os.pipeline import write_artifacts

from conftest import ROOT, VOCAL_CHOP_FIXTURE

SAMPLE_TREES = {
    "halee_ramone": ROOT / "examples" / "sample_output",
    "timbaland": ROOT / "examples" / "sample_output_timbaland",
}

# The ONE normalization the comparison needs: two artifacts
# (source_material.json, track_analysis.json) echo the stems path exactly
# as it was given on the command line. The committed trees were generated
# from the repo root with the PORTABLE relative form (committed artifacts
# must never carry a machine's absolute paths); the session fixture
# analyzes via an absolute path. Rewriting that one input echo — nothing
# else — makes the comparison byte-exact on all 30 files.
_STEMS_REL = f"fixtures/{VOCAL_CHOP_FIXTURE}/stems"
_STEMS_ABS = str(ROOT / "fixtures" / VOCAL_CHOP_FIXTURE / "stems")


def _normalized(path):
    return path.read_bytes().replace(
        _STEMS_ABS.encode("utf-8"), _STEMS_REL.encode("utf-8")
    )


# The README table's values — the established pins (P-035/P-039:
# tests/test_vocal_chop_groove.py, tests/test_producer_cli.py).
HEADLINES = {
    "halee_ramone": {
        "overall_mix_readiness_score": 76.3,
        "vocal_role_fit_score": 65.0,
        "loop_context_score": 15.0,
    },
    "timbaland": {
        "overall_mix_readiness_score": 60.9,
        "vocal_role_fit_score": 85.0,
        "loop_context_score": 10.0,
    },
}


@pytest.mark.parametrize("producer", sorted(SAMPLE_TREES))
def test_committed_sample_trees_match_a_fresh_run(
    producer, chop_groove_analyzed, tmp_path
):
    """THE STALENESS PIN: the committed tree IS a fresh run — same file-name
    set, every one of the 30 artifacts byte-identical to ``write_artifacts``
    on the session's own analysis of the same fixture (modulo the documented
    stems-path input echo — see ``_normalized``). The committed trees stay
    portable: no absolute path anywhere in them."""
    committed = SAMPLE_TREES[producer]
    fresh = tmp_path / "fresh"
    write_artifacts(chop_groove_analyzed[producer], fresh)

    committed_files = sorted(p.name for p in committed.iterdir() if p.is_file())
    fresh_files = sorted(p.name for p in fresh.iterdir() if p.is_file())
    assert committed_files == fresh_files, producer
    assert len(committed_files) == 30, producer
    for name in committed_files:
        committed_bytes = (committed / name).read_bytes()
        assert _STEMS_ABS.encode("utf-8") not in committed_bytes, (producer, name)
        assert committed_bytes == _normalized(fresh / name), (producer, name)


@pytest.mark.parametrize("producer", sorted(SAMPLE_TREES))
def test_committed_sample_headlines_are_the_pinned_values(producer):
    """The committed doctrine_score.json files carry the README table's
    numbers and each tree names ITS OWN producer (machine-readable identity +
    the human-readable verdict line near the top of mix_verdict.md)."""
    tree = SAMPLE_TREES[producer]
    ds = json.loads((tree / "doctrine_score.json").read_text(encoding="utf-8"))
    for key, value in HEADLINES[producer].items():
        assert ds[key] == value, (producer, key)
    assert ds["producer"]["name"] == producer

    verdict_line = (
        (tree / "mix_verdict.md").read_text(encoding="utf-8").splitlines()[2]
    )
    assert f"({producer})" in verdict_line
    assert verdict_line.startswith("**Producer profile:**")
