"""P-040 / P-046 — THE SAMPLE REFRESH: the committed producer demo trees.

``examples/`` carries the differential in committed form — FOUR artifact
trees generated by the real CLI from the SAME stems (the seeded
``vocal_chop_groove`` fixture, the differential's showcase). P-040 committed
the first two; P-046 added the second pair when the producer roster grew
(quincy_jones P-041, brian_eno P-045):

    examples/sample_output/            <- the reference run (halee_ramone)
    examples/sample_output_timbaland/  <- --producer timbaland
    examples/sample_output_quincy/     <- --producer quincy_jones   (P-046)
    examples/sample_output_eno/        <- --producer brian_eno      (P-046)

Each tree is the output of exactly one verbatim invocation from the
project root (after ``python fixtures/generate_fixtures.py``) — the same
four invocations the README quotes:

    python -m logic_mix_os.cli analyze \\
      --stems fixtures/vocal_chop_groove/stems \\
      --manifest fixtures/vocal_chop_groove/project_manifest.json \\
      --out <tree> [--producer timbaland|quincy_jones|brian_eno]

THE STALENESS PIN (the packet's judgment call, taken at FULL strength):
each committed tree must byte-match a freshly generated run — the same
file-name set, every file byte-identical, modulo exactly ONE documented
normalization (the stems-path input echo in two artifacts — the committed
trees carry the portable relative form). The P-038 standing note this
packet clears existed because the old sample tree shipped stale
pre-P-036/P-038 prose from an earlier fixture/contract era; with this pin
the samples can never silently rot again. Full-tree comparison is CHEAP
here by construction: two of the four analyses are the session-scoped
``chop_groove_analyzed`` fixture (already computed for the P-035/P-032i
suites), the quincy/eno pair is a module-scoped run of the same fixture
(the ``sample_analyses`` map below), and ``write_artifacts`` is pure
rendering — and P-039 pinned that the CLI tree byte-matches the library
``write_artifacts`` tree, so the library run is an honest stand-in for the
committed trees' actual CLI provenance. Determinism is real (seeded
fixture; two consecutive CLI regenerations were byte-identical at commit
time for every tree).

The headline pin re-reads the committed files DIRECTLY: the README's
"Four producers, same stems" table quotes exactly these values, so the
docs' claims stay machine-checked even though the staleness pin already
implies them transitively. The mode-surface pin (P-046) does the same for
the README's "Modes are behavior" claims: which committed trees carry an
authored declaration/fork surface, which extended candidate each reach
admits, and every tree's branch winners.
"""

from __future__ import annotations

import json

import pytest

from logic_mix_os.pipeline import analyze, write_artifacts
from logic_mix_os.project import load_manifest

from conftest import ROOT, VOCAL_CHOP_FIXTURE

SAMPLE_TREES = {
    "halee_ramone": ROOT / "examples" / "sample_output",
    "timbaland": ROOT / "examples" / "sample_output_timbaland",
    "quincy_jones": ROOT / "examples" / "sample_output_quincy",
    "brian_eno": ROOT / "examples" / "sample_output_eno",
    "chris_lord_alge": ROOT / "examples" / "sample_output_chris_lord_alge",
}

# THE ALLOWED ``examples/``-LEVEL RESIDENT SET beyond the sample trees
# (P-049), enumerated CONSCIOUSLY from the real directory: the mode-demo
# home (its own residents guarded resident-by-resident in
# tests/test_mode_demo_refresh.py) and the manifest-format example the
# README documents. Nothing else lives at that level at pin time.
EXAMPLES_ROOT = ROOT / "examples"
NON_TREE_RESIDENTS = {"mode_demos", "project_manifest.example.json"}

# The ONE normalization the comparison needs: two artifacts
# (source_material.json, track_analysis.json) echo the stems path exactly
# as it was given on the command line. The committed trees were generated
# from the repo root with the PORTABLE relative form (committed artifacts
# must never carry a machine's absolute paths); the session fixture
# analyzes via an absolute path. Rewriting that one input echo — nothing
# else — makes the comparison byte-exact on all 30 files.
_STEMS_REL = f"fixtures/{VOCAL_CHOP_FIXTURE}/stems"
_STEMS_ABS = str(ROOT / "fixtures" / VOCAL_CHOP_FIXTURE / "stems")


def _normalized(path):
    return path.read_bytes().replace(
        _STEMS_ABS.encode("utf-8"), _STEMS_REL.encode("utf-8")
    )


# The README table's values — the established pins (P-035/P-039:
# tests/test_vocal_chop_groove.py, tests/test_producer_cli.py; P-041/P-045:
# the quincy/eno columns agree with THREE_WAY_OVERALLS / FOUR_WAY_OVERALLS
# in tests/test_three_way_differential.py / tests/test_four_way_differential.py).
HEADLINES = {
    "halee_ramone": {
        "overall_mix_readiness_score": 76.3,
        "vocal_role_fit_score": 65.0,
        "loop_context_score": 15.0,
    },
    "timbaland": {
        "overall_mix_readiness_score": 60.9,
        "vocal_role_fit_score": 85.0,
        "loop_context_score": 10.0,
    },
    "quincy_jones": {
        "overall_mix_readiness_score": 68.2,
        "vocal_role_fit_score": 85.0,
        "loop_context_score": 12.0,
    },
    "brian_eno": {
        "overall_mix_readiness_score": 64.3,
        "vocal_role_fit_score": 85.0,
        "loop_context_score": 35.0,
    },
    # P-053: the fifth producer. His overall agrees with the five-way pin
    # (67.8); vocal_role_fit reads 85.0 (his authored vocal-blend opt-in,
    # the same masking involvements the other three profiles accept) and
    # loop_context 18.0 — his own authored value for the STATIC dominant
    # chop loop ("commit to it and drive it": doctrine 18.0, above the
    # reference's clarity-protecting 15.0, below eno's ambient-bed 35.0).
    "chris_lord_alge": {
        "overall_mix_readiness_score": 67.8,
        "vocal_role_fit_score": 85.0,
        "loop_context_score": 18.0,
    },
}

# THE MODE SURFACE OF EACH COMMITTED TREE (P-046) — what each producer's
# DEFAULT mode authored, echoed in creative.json. On this fixture the
# reference (dramatic_contrast) and eno (horizontal_time) run
# authored-neutral defaults: zero declaration keys, zero per-branch fork
# keys (the P-042 byte-silence discipline). Timbaland's dramatic_contrast
# declares dropout reach (the conscious P-044 drift); quincy's default is
# the mode literally named arrangement_lift and declares that family's
# reach (P-043). The declaration shape matches the standing live-engine
# pins (tests/test_negative_space_dropout.py,
# tests/test_move_vocabulary_expansion.py).
DECLARATIONS = {
    "halee_ramone": None,
    "timbaland": {
        "allowed_risk": "medium", "favor_kinds": [], "suppress_kinds": [],
        "reach_kinds": ["negative_space_dropout"],
    },
    "quincy_jones": {
        "allowed_risk": "medium", "favor_kinds": [], "suppress_kinds": [],
        "reach_kinds": ["arrangement_lift"],
    },
    "brian_eno": None,
    # CLA's default mode (commit_and_slam) authors a medium risk posture but
    # zero favor / suppress / reach — so it is byte-silent, the P-042
    # discipline (like the reference and eno): no declaration key, no
    # per-branch fork key. His forking shows in his EXPLICIT modes (the
    # committed mode demos), not his default.
    "chris_lord_alge": None,
}

# The extended candidate each authored reach admits into the chorus_lift
# branch (None = the engine's neutral candidate set only). The full
# extended-id universe on this fixture's branches, for the no-leak half.
REACH_CANDIDATE = {
    "halee_ramone": None,
    "timbaland": "chorus_lift_F",     # negative_space_dropout (P-044)
    "quincy_jones": "chorus_lift_E",  # arrangement_lift (P-043)
    "brian_eno": None,
    "chris_lord_alge": None,           # commit_and_slam reaches nothing
}
EXTENDED_IDS = {"chorus_lift_E", "chorus_lift_F", "vocal_C",
                "density_C", "density_D", "density_E"}

# Every committed tree's branch winners — the README's honesty statement.
# The four ORIGINAL producers land the same non-vocal winners
# (chorus_lift_B / loop_B / depth_A — both B's are subtractive_drop moves);
# they diverge only on vocal_belief (eno's intimacy pass wins vocal_B, the
# P-045 pin; the other three ride the phrase, vocal_A). P-053: CLA is the
# FIRST producer whose DEFAULT plan choice diverges on the non-vocal
# branches — his impact/commitment posture wins the drum-room move
# (chorus_lift_D) over the subtractive one and loop_deconstruct (loop_A)
# over the subtractive loop move, WITHOUT any iconic-loop reading, straight
# from his weighting. Re-read from the committed bytes.
WINNERS = {
    "halee_ramone": {"chorus_lift": "chorus_lift_B", "loop": "loop_B",
                     "depth": "depth_A", "vocal_belief": "vocal_A"},
    "timbaland": {"chorus_lift": "chorus_lift_B", "loop": "loop_B",
                  "depth": "depth_A", "vocal_belief": "vocal_A"},
    "quincy_jones": {"chorus_lift": "chorus_lift_B", "loop": "loop_B",
                     "depth": "depth_A", "vocal_belief": "vocal_A"},
    "brian_eno": {"chorus_lift": "chorus_lift_B", "loop": "loop_B",
                  "depth": "depth_A", "vocal_belief": "vocal_B"},
    "chris_lord_alge": {"chorus_lift": "chorus_lift_D", "loop": "loop_A",
                        "depth": "depth_A", "vocal_belief": "vocal_A"},
}


@pytest.fixture(scope="module")
def sample_analyses(chop_groove_analyzed):
    """The five-producer map over the demo fixture: the session-scoped pair
    (halee_ramone, timbaland — conftest's ``chop_groove_analyzed``) plus
    module-scoped quincy/eno/chris_lord_alge runs, each resolved dynamically
    by name (the P-041/P-045/P-053 no-code-changes clause)."""
    manifest = load_manifest(
        ROOT / "fixtures" / VOCAL_CHOP_FIXTURE / "project_manifest.json"
    )
    stems = str(ROOT / "fixtures" / VOCAL_CHOP_FIXTURE / "stems")
    results = dict(chop_groove_analyzed)
    for producer in ("quincy_jones", "brian_eno", "chris_lord_alge"):
        results[producer] = analyze(stems, manifest, producer=producer)
    return results


@pytest.mark.parametrize("producer", sorted(SAMPLE_TREES))
def test_committed_sample_trees_match_a_fresh_run(
    producer, sample_analyses, tmp_path
):
    """THE STALENESS PIN: the committed tree IS a fresh run — same file-name
    set, every one of the 30 artifacts byte-identical to ``write_artifacts``
    on the session's own analysis of the same fixture (modulo the documented
    stems-path input echo — see ``_normalized``). The committed trees stay
    portable: no absolute path anywhere in them."""
    committed = SAMPLE_TREES[producer]
    fresh = tmp_path / "fresh"
    write_artifacts(sample_analyses[producer], fresh)

    # THE NESTED-SUBDIR MICRO-HARDENING (P-049 reviewer note, folded in at
    # P-053): the file-set comparison below filters ``is_file()`` on both
    # sides, so a stray nested subdirectory inside a committed
    # ``sample_output*`` tree would escape the byte comparison entirely.
    # A committed sample tree is FLAT — 30 files, zero subdirectories — so
    # assert it directly; a nested stray dir now fails loudly.
    assert not any(p.is_dir() for p in committed.iterdir()), producer

    committed_files = sorted(p.name for p in committed.iterdir() if p.is_file())
    fresh_files = sorted(p.name for p in fresh.iterdir() if p.is_file())
    assert committed_files == fresh_files, producer
    assert len(committed_files) == 30, producer
    for name in committed_files:
        committed_bytes = (committed / name).read_bytes()
        assert _STEMS_ABS.encode("utf-8") not in committed_bytes, (producer, name)
        assert committed_bytes == _normalized(fresh / name), (producer, name)


@pytest.mark.parametrize("producer", sorted(SAMPLE_TREES))
def test_committed_sample_headlines_are_the_pinned_values(producer):
    """The committed doctrine_score.json files carry the README table's
    numbers and each tree names ITS OWN producer (machine-readable identity +
    the human-readable verdict line near the top of mix_verdict.md)."""
    tree = SAMPLE_TREES[producer]
    ds = json.loads((tree / "doctrine_score.json").read_text(encoding="utf-8"))
    for key, value in HEADLINES[producer].items():
        assert ds[key] == value, (producer, key)
    assert ds["producer"]["name"] == producer

    verdict_line = (
        (tree / "mix_verdict.md").read_text(encoding="utf-8").splitlines()[2]
    )
    assert f"({producer})" in verdict_line
    assert verdict_line.startswith("**Producer profile:**")


@pytest.mark.parametrize("producer", sorted(SAMPLE_TREES))
def test_committed_sample_mode_surface_is_the_authored_reach(producer):
    """THE MODE-SURFACE PIN (P-046): each committed tree's creative.json
    carries exactly its producer's authored default-mode surface — the
    declaration echo and per-branch fork reports where the default authored
    a reach (timbaland: dropout; quincy: arrangement_lift, admitting
    exactly one extended chorus_lift candidate each), byte-silence where it
    did not (the reference and eno) — and every tree's branch winners are
    the pinned non-extended moves: the reach widens candidate sets, never
    the verdicts."""
    tree = SAMPLE_TREES[producer]
    cr = json.loads((tree / "creative.json").read_text(encoding="utf-8"))

    declared = DECLARATIONS[producer]
    if declared is None:
        assert "search_mode_declarations" not in cr
        for b in cr["branches"]:
            assert "mode_fork" not in b, b["problem_id"]
    else:
        assert cr["search_mode_declarations"] == declared
        for b in cr["branches"]:
            expected = (declared["reach_kinds"]
                        if b["problem_id"] == "chorus_lift" else [])
            assert b["mode_fork"]["reached"] == expected, b["problem_id"]
            assert b["mode_fork"]["reach_capped"] == [], b["problem_id"]

    ids = {b["problem_id"]: [v["variant_id"] for v in b["variants"]]
           for b in cr["branches"]}
    admitted = REACH_CANDIDATE[producer]
    if admitted is not None:
        assert admitted in ids["chorus_lift"]
    all_ids = {vid for branch_ids in ids.values() for vid in branch_ids}
    assert all_ids & EXTENDED_IDS == ({admitted} - {None}), producer

    winners = {b["problem_id"]: b["winning"]["winning_variant"]
               for b in cr["branches"]}
    assert winners == WINNERS[producer]


def test_committed_examples_directory_set_is_exactly_the_pinned_residents():
    """THE DIRECTORY-SET GUARD (P-049): the committed sample-tree set under
    ``examples/`` is EXACTLY the five pinned trees (P-053 added the fifth,
    chris_lord_alge, via the one-line SAMPLE_TREES extension this guard was
    designed for) — SAMPLE_TREES' own directories, so this guard derives
    from the same table every pin above parametrizes over and can never
    drift from the pins it protects — and the FULL ``examples/``-level
    resident set is exactly those trees plus the consciously enumerated
    NON_TREE_RESIDENTS. It fails LOUDLY on a new unpinned tree (which would
    ship staleness-unpinned), on a deleted pinned tree, and on any stray
    file or dir at that level. A legitimate sixth tree later is a CONSCIOUS
    one-line SAMPLE_TREES extension — which automatically brings the
    staleness/headline/mode-surface pins above to the newcomer; a new
    non-tree resident is a conscious NON_TREE_RESIDENTS extension; anything
    failing here without one of those is a stray committed artifact."""
    tree_names = {path.name for path in SAMPLE_TREES.values()}
    assert len(tree_names) == len(SAMPLE_TREES), tree_names
    assert all(p.parent == EXAMPLES_ROOT for p in SAMPLE_TREES.values())

    residents = sorted(p.name for p in EXAMPLES_ROOT.iterdir())
    assert residents == sorted(tree_names | NON_TREE_RESIDENTS), residents

    dirs = sorted(p.name for p in EXAMPLES_ROOT.iterdir() if p.is_dir())
    assert dirs == sorted(tree_names | {"mode_demos"}), dirs
